### ISSUE TITLE
Pass through portal not working

### ISSUE THREAD

**Issue by sramonpacheco** [basti564/vrLauncher#11]
1. Was using the passthrough portal for last and previous sessions.
2. This time, the portal only displayed a blue border from where I expected the passthrough to display.
3. Then updated to the latest 1.5 update but it didn't behave any different.

Suddenly noticed the passthrough portal only enabling when leaning over into the outlined keyboard space where the passthrough behaved like the glanceable boundary. 

I only use Quest for working and now the keyboard is gone. Any ideas? Could this be due to the v30 quest update conflicting? Also saw Couch mode act oddly and enable in place of passthrough portal without turning it on.

Other people with a similar issue: https://www.reddit.com/r/OculusQuest/comments/o3uu5e/are_passthrough_portals_still_working/

**Comment by ptrpaws** [comment]
It seems like they changed the behavior of the passthrough portal. The app couldn't change anything as I'm just redirecting you to the creation dialogue, my app doesn't have any of the passthrough portal code. Something interesting I noted, was that it does behave differently when you are at a desk space then when you are using it without it.
I can't change anything about it not working, Oculus would need to fix that :/

**Comment by sramonpacheco** [comment]
Totally understandable.

Thanks so much for the follow up and feedback. I really hope Oculus allows
access again. I loved it while it lasted but most of all, thank you for
creating it. Great work.

**Comment by ptrpaws** [comment]
Passthrough Portal got completely removed in v31

**Comment by sramonpacheco** [comment]
Yep. I saw this. It must be because the new dev access I imagine. I thought
of you when I saw this.

I appreciate your email my friend! Maybe I can help you in the future and
we can work together.
