### ISSUE TITLE
not a issues just a question 

### ISSUE THREAD

**Issue by wolf-tech07** [basti564/vrLauncher#14]
are all the things that you removed from v33 good

**Comment by Firepal** [comment]
Oculus is responsible for system updates, not @basti564.

**Comment by wolf-tech07** [comment]
> Oculus is responsible for system updates, not @basti564.

yes but it say's when you go to install the app

v33 removed:
APP_LAUNCH_BLOCKED_CONTROLLER_REQUIRED
APP_MODE_INCOMPATIBLE
CAPTIVE_WIFI_PORTAL
CONTROLLER_PAIRING
INSTALLER
KEYBOARD
LAUNCH_CHECK_APP_DEGRADED
LAUNCH_CHECK_APP_DISABLED
LAUNCH_CHECK_APP_UPDATE
LAUNCH_CHECK_BLOCK_DESK
LAUNCH_CHECK_CLOUD_STORAGE
LAUNCH_CHECK_REQUIRES_6DOF
LAUNCH_CHECK_REQUIRES_AVATAR
LAUNCH_CHECK_REQUIRES_CONTROLLERS
LAUNCH_CHECK_REQUIRES_DESK
LAUNCH_CHECK_REQUIRES_EXCLUSIVE_MICROPHONE
LAUNCH_CHECK_REQUIRES_HANDS
LIVESTREAMING
LOCAL_STREAM_PRIVACY_CHECK_DIALOG
LOCAL_STREAM_TO_BROWSER_DIALOG
NONE
OCULUS_LINK_AVAILABLE
OCULUS_LINK_DISCONNECTED
PANEL_REORIENT
QUIT_AND_LAUNCH
SOCIAL_ADD_FRIENDS
SYSTEM_FAILURE_MESSAGE
TRACKING_MODE_3DOF_INCOMPAT_DIALOG
UNINSTALLER
UNIVERSAL_SHARE_SHEET
UNOFFICIAL_APP_INSTALLED_DIALOG
UNOFFICIAL_APP_LAUNCHED_DIALOG
USER_PROFILE

is the app removeing these or is it stuff that oculus Removed in v33.if it's stuff that the app removes  is it good ?

**Comment by ptrpaws** [comment]
> > Oculus is responsible for system updates, not @basti564.
> 
> 
> 
> yes but it say's when you go to install the app
> 
> 
> 
> v33 removed:
> 
> APP_LAUNCH_BLOCKED_CONTROLLER_REQUIRED
> 
> APP_MODE_INCOMPATIBLE
> 
> CAPTIVE_WIFI_PORTAL
> 
> CONTROLLER_PAIRING
> 
> INSTALLER
> 
> KEYBOARD
> 
> LAUNCH_CHECK_APP_DEGRADED
> 
> LAUNCH_CHECK_APP_DISABLED
> 
> LAUNCH_CHECK_APP_UPDATE
> 
> LAUNCH_CHECK_BLOCK_DESK
> 
> LAUNCH_CHECK_CLOUD_STORAGE
> 
> LAUNCH_CHECK_REQUIRES_6DOF
> 
> LAUNCH_CHECK_REQUIRES_AVATAR
> 
> LAUNCH_CHECK_REQUIRES_CONTROLLERS
> 
> LAUNCH_CHECK_REQUIRES_DESK
> 
> LAUNCH_CHECK_REQUIRES_EXCLUSIVE_MICROPHONE
> 
> LAUNCH_CHECK_REQUIRES_HANDS
> 
> LIVESTREAMING
> 
> LOCAL_STREAM_PRIVACY_CHECK_DIALOG
> 
> LOCAL_STREAM_TO_BROWSER_DIALOG
> 
> NONE
> 
> OCULUS_LINK_AVAILABLE
> 
> OCULUS_LINK_DISCONNECTED
> 
> PANEL_REORIENT
> 
> QUIT_AND_LAUNCH
> 
> SOCIAL_ADD_FRIENDS
> 
> SYSTEM_FAILURE_MESSAGE
> 
> TRACKING_MODE_3DOF_INCOMPAT_DIALOG
> 
> UNINSTALLER
> 
> UNIVERSAL_SHARE_SHEET
> 
> UNOFFICIAL_APP_INSTALLED_DIALOG
> 
> UNOFFICIAL_APP_LAUNCHED_DIALOG
> 
> USER_PROFILE
> 
> 
> 
> is the app removeing these or is it stuff that oculus Removed in v33.if it's stuff that the app removes  is it good ?

It's stuff Oculus removed it v33. If you are still on v32 you can still use it in the app after you selected v32 with the version selector.

**Comment by wolf-tech07** [comment]
thanks
