### ISSUE TITLE
current quest 2 version 34, not compatible w/ latest version on app which is version 32

### ISSUE THREAD

**Issue by JsonTyler** [basti564/vrLauncher#16]
When I click on any setting and then push "go" the app just crashes and reloads into my home screen outside of the app.

**Comment by ptrpaws** [comment]
Hmm, the latest app version v1.8 for up to v33. I'll update the app to add support for v34 today. What v34 changes that the screen blacks out for a second, but it doesn't crash and the actions still work. I'm not sure if I can prevent closing the app with the way it works, you can maybe try the back button to reopen the app.

**Comment by ptrpaws** [comment]
updated it to [v1.9](https://github.com/basti564/vrLauncher/releases/tag/v1.9)
