### ISSUE TITLE
How can you turn off PASSTHROUGH_PORTAL?

### ISSUE THREAD

**Issue by Evolvingmonkeys** [basti564/vrLauncher#4]
I now have a floating passthrough surface that is persistent through all apps and games, as well as the menu.  Any solutions?  I tried turning off experimental features, which turned off the couch, but not the keyboard portal.  
Thanks for your awesome work!

**Comment by ptrpaws** [comment]
You should be able to remove it by clearing your guardian history, but you can also try to disable it by opening the passthrough portal menu again and clicking on "remove"
