### ISSUE TITLE
Need to test with v28

### ISSUE THREAD

**Issue by emilyastranova** [basti564/vrLauncher#5]
I'm not sure how to find the intents you found @basti564 . Any help? I have v28 now.

**Comment by ptrpaws** [comment]
I have already told you on Discord, but for everyone else:
Pull the SystemUX apk from the Quest via adb:
```adb pull /system/priv-app/SystemUX/SystemUX.apk```
Decompile it via jadx.
You will find the intents in sources\com}oculus\vrshell\SystemUXRoute.java

**Comment by caffeinum** [comment]
would the current apk would with v28?

**Comment by ptrpaws** [comment]
> would the current apk would with v28?

Yes, the current release works with v28 https://github.com/basti564/vrLauncher/releases/tag/v1.3

**Comment by caffeinum** [comment]
Thanks! It works flawlessly
