### ISSUE TITLE
What to do with json file?

### ISSUE THREAD

**Issue by WilsonBradley** [basti564/vrLauncher#7]
Hate to be a noob here , but under the files, could you explain what to do with the output-meta.json file?

Thanks..

**Comment by ptrpaws** [comment]
Hey @WilsonBradley, the output-meta.json just contains meta information about the build. You don't have to do anything with it, as it just information about the app like the version and and some other stuff not needed to run the app :)

**Comment by WilsonBradley** [comment]
Thank you so much for the reply. 
Good to know.
